services:
  testDb:
    image: postgres:17.4
    container_name: test-db
    environment:
      POSTGRES_USER: mounis
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    volumes:
      - test_db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
  test_db_data: