name: Deploy Workout API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.0"

      - name: Install Swagger CLI
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Update host for production
        run: |
          sed -i 's/@host\s*localhost:8080/@host workouts.mounis.net/' main.go
          sed -i 's/@schemes\s*http/@schemes https/' main.go

      - name: Generate Swagger documentation
        run: swag init

      - name: Install dependencies
        run: go mod download

      - name: Build Go binary
        run: |
          mkdir -p dist
          go build -o dist/workout-api .

      - name: Create .env file with DATABASE_URL
        run: |
          echo "DATABASE_URL=${DATABASE_URL}" > dist/.env

      - name: Copy docs to dist
        run: |
          cp -r docs dist/

      - name: Deploy binary, docs, and .env to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: "dist/*"
          target: "/var/www/workouts-api"

      - name: Restart workout-api service
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            sudo /bin/systemctl restart workout-api.service
